language: java

script: mvn -Dhttpclient.version=$HTTPCLIENT_VERSION clean verify

jdk:
  - openjdk7

env:
  - HTTPCLIENT_VERSION=4.1
  - HTTPCLIENT_VERSION=4.2
  - HTTPCLIENT_VERSION=4.3.4

notifications:
  email:
    - dsmiley@apache.org
